[package]
name = "multisignal"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/VesperXlabs/MultiSignal"
homepage = "https://vesperx.dk"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "0.11.5", package = "gtk4", features = ["v4_14"] }
thiserror = "2.0.20"

[dev-dependencies]
tempfile = "3.27.0"

[[test]]
name = "ui"
harness = false

[profile.release]
strip = true
